//
//  Settings.swift
//  PasteMine
//
//  Created by lagrange on 2025/11/22.
//

import Foundation

/// 忽略的应用信息
struct IgnoredApp: Codable, Identifiable, Equatable {
    var id: String { bundleId }
    let bundleId: String        // Bundle Identifier (用于匹配)
    let displayName: String     // 显示名称 (用于界面显示)
    
    static func == (lhs: IgnoredApp, rhs: IgnoredApp) -> Bool {
        lhs.bundleId == rhs.bundleId
    }
}

struct AppSettings: Codable {
    var notificationEnabled: Bool = true
    var soundEnabled: Bool = true  // 音效开关
    var launchAtLogin: Bool = false  // 开机自启动
    var globalShortcut: KeyboardShortcut = .defaultShortcut  // 默认 ⌘⇧V
    var maxHistoryCount: Int = 50  // 默认 50 条
    var ignoreLargeImages: Bool = false  // 是否忽略大图片（>20MB）
    
    // 隐私设置
    var ignoredApps: [IgnoredApp] = []  // 忽略的应用列表
    var ignoredPasteboardTypes: [String] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    ]  // 忽略的剪贴板类型列表
    var ignoreTypesEnabled: Bool = false  // 是否启用忽略类型功能（默认关闭）
    var clearOnQuit: Bool = false  // 退出时清空剪贴板
    
    // 存储到 UserDefaults
    static let key = "app_settings"
    
    /// 从 UserDefaults 加载设置
    static func load() -> AppSettings {
        guard let data = UserDefaults.standard.data(forKey: key),
              let settings = try? JSONDecoder().decode(AppSettings.self, from: data) else {
            return AppSettings()
        }
        return settings
    }
    
    /// 保存设置到 UserDefaults
    func save() {
        if let data = try? JSONEncoder().encode(self) {
            UserDefaults.standard.set(data, forKey: Self.key)
        }
        
        // 通知快捷键已更改
        NotificationCenter.default.post(name: .shortcutDidChange, object: nil)
    }

    /// 历史记录数量选项
    static let historyCountOptions = [50, 200, 999]

    /// 大图片阈值（20MB）
    static let largeImageThreshold = 20
}

